"use client";

import { useEffect, useMemo, useState } from "react";
import { AppShell } from "../shell";
import { apiFetch, daysBetween, downloadCsv, formatDate } from "../lib";
import { AlertMark, Badge, EmptyState, SkeletonRows, buttonClass, inputClass, panelClass } from "../ui";
import { RecordDetailModal } from "../record-detail-modal";

interface Movement { id: string; reference_number: string; item_category: string; type: string; entry_date: string; exit_date: string | null; status: string; chassis_number: string | null; bond_value_tzs: string | null; vehicle_description: string | null; active_alert: boolean; active_alert_id: string | null }
interface Extension { id: string; requested_date: string; extended_until: string; status: string; active_alert: boolean; active_alert_id: string | null; movement: Movement }
interface Invoice { id: string; amount: string; issued_date: string; due_date: string; paid_date: string | null; status: string; active_alert: boolean; active_alert_id: string | null; movement: Movement }
interface WarehouseData { movements: Movement[]; extensions: Extension[]; invoices: Invoice[] }
const tabs = ["Movements", "Extensions", "Invoices"] as const;

export default function WarehousePage() {
  const [data, setData] = useState<WarehouseData>({ movements: [], extensions: [], invoices: [] }); const [tab, setTab] = useState<typeof tabs[number]>("Movements"); const [search, setSearch] = useState(""); const [fromDate, setFromDate] = useState(""); const [toDate, setToDate] = useState(""); const [payment, setPayment] = useState(""); const [loading, setLoading] = useState(true); const [exporting, setExporting] = useState(false); const [selected, setSelected] = useState<{ type: "movement" | "extension" | "invoice"; id: string } | null>(null); const [error, setError] = useState("");
  async function load() { try { setData(await apiFetch<WarehouseData>("/warehouse")); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to load warehouse"); } finally { setLoading(false); } }
  useEffect(() => { load(); }, []);
  const query = search.toLowerCase();
  const inDateRange = (value: string) => (!fromDate || value.slice(0, 10) >= fromDate) && (!toDate || value.slice(0, 10) <= toDate);
  const rows = useMemo(() => tab === "Movements" ? data.movements.filter((row) => `${row.reference_number} ${row.item_category} ${row.type} ${row.chassis_number ?? ""} ${row.vehicle_description ?? ""}`.toLowerCase().includes(query) && inDateRange(row.entry_date)) : tab === "Extensions" ? data.extensions.filter((row) => row.movement.reference_number.toLowerCase().includes(query)) : data.invoices.filter((row) => row.movement.reference_number.toLowerCase().includes(query) && inDateRange(row.issued_date) && (!payment || (payment === "paid" ? Boolean(row.paid_date) : !row.paid_date))), [data, fromDate, payment, query, tab, toDate]);
  async function exportReport() { if (tab === "Extensions") return; setExporting(true); setError(""); try { const params = new URLSearchParams(); if (search) params.set("search", search); if (fromDate) params.set("from", fromDate); if (toDate) params.set("to", toDate); if (tab === "Invoices" && payment) params.set("payment", payment); const resource = tab === "Invoices" ? "invoices" : "movements"; await downloadCsv(`/reports/${resource}.csv?${params}`, `ajs-warehouse-${resource}.csv`); } catch (caught) { setError(caught instanceof Error ? caught.message : "Unable to export report"); } finally { setExporting(false); } }
  return <AppShell eyebrow="Bonded compliance" title="Warehouse"><section className={panelClass}><div className="flex flex-col gap-4 border-b border-ajs-border p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-end lg:justify-between"><div className="flex overflow-x-auto rounded-lg border border-ajs-border bg-ajs-bg p-1">{tabs.map((name) => <button className={`min-h-10 rounded-md px-4 text-xs font-bold ${tab === name ? "bg-ajs-accent text-white" : "text-ajs-secondary hover:text-white"}`} onClick={() => setTab(name)} key={name}>{name}</button>)}</div><div className="flex flex-wrap items-end gap-2"><input aria-label={`Search ${tab}`} className={`${inputClass} sm:w-64`} placeholder={`Search ${tab.toLowerCase()}…`} value={search} onChange={(event) => setSearch(event.target.value)} />{tab !== "Extensions" ? <><label className="text-xs text-ajs-secondary">From<input className={`${inputClass} mt-1 block w-36`} type="date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} /></label><label className="text-xs text-ajs-secondary">To<input className={`${inputClass} mt-1 block w-36`} type="date" value={toDate} onChange={(event) => setToDate(event.target.value)} /></label>{tab === "Invoices" ? <label className="text-xs text-ajs-secondary">Payment<select className={`${inputClass} mt-1 block`} value={payment} onChange={(event) => setPayment(event.target.value)}><option value="">All</option><option value="paid">Paid</option><option value="unpaid">Unpaid</option></select></label> : null}<button className={buttonClass} disabled={exporting} onClick={exportReport}>{exporting ? "Exporting…" : "Export CSV"}</button></> : null}</div></div></div>{error ? <p className="m-4 text-red-300">{error}</p> : null}{loading ? <SkeletonRows /> : rows.length === 0 ? <div className="p-5"><EmptyState title={`No ${tab.toLowerCase()} found`} detail="Warehouse records will appear here as operations are entered." /></div> : tab === "Movements" ? <MovementRows onOpen={(id) => setSelected({ type: "movement", id })} rows={rows as Movement[]} /> : tab === "Extensions" ? <ExtensionRows onOpen={(id) => setSelected({ type: "extension", id })} rows={rows as Extension[]} /> : <InvoiceRows onOpen={(id) => setSelected({ type: "invoice", id })} rows={rows as Invoice[]} />}</section>{selected ? <RecordDetailModal recordId={selected.id} type={selected.type} onChanged={load} onClose={() => setSelected(null)} /> : null}</AppShell>;
}

function MovementRows({ rows, onOpen }: { rows: Movement[]; onOpen: (id: string) => void }) { const money = new Intl.NumberFormat("en-TZ", { style: "currency", currency: "TZS", maximumFractionDigits: 0 }); return <Table headers={["TANSAD", "Chassis", "Description", "Bond value", "Category", "Entry date", "Days stored", "Status", "Alert"]} onOpen={onOpen} rows={rows.map((row) => ({ id: row.id, cells: [<strong>{row.reference_number}</strong>, <span className="font-mono text-xs">{row.chassis_number ?? "—"}</span>, <span className="line-clamp-2">{row.vehicle_description ?? "—"}</span>, row.bond_value_tzs ? money.format(Number(row.bond_value_tzs)) : "—", <Badge value={row.item_category} />, formatDate(row.entry_date), <span className={daysBetween(row.entry_date, row.exit_date ? new Date(row.exit_date) : new Date()) > 170 ? "font-bold text-red-300" : ""}>{daysBetween(row.entry_date, row.exit_date ? new Date(row.exit_date) : new Date())} days</span>, <Badge value={row.status} />, <AlertMark active={row.active_alert} />] }))} />; }
function ExtensionRows({ rows, onOpen }: { rows: Extension[]; onOpen: (id: string) => void }) { return <Table headers={["Movement", "Requested", "Extended until", "Days remaining", "Status", "Alert"]} onOpen={onOpen} rows={rows.map((row) => ({ id: row.id, cells: [<strong>{row.movement.reference_number}</strong>, formatDate(row.requested_date), formatDate(row.extended_until), <span>{-daysBetween(row.extended_until)} days</span>, <Badge value={row.status} />, <AlertMark active={row.active_alert} />] }))} />; }
function InvoiceRows({ rows, onOpen }: { rows: Invoice[]; onOpen: (id: string) => void }) { const money = new Intl.NumberFormat("en-TZ", { style: "currency", currency: "TZS", maximumFractionDigits: 0 }); return <Table headers={["Movement", "Amount", "Issued", "Due", "Days overdue", "Paid", "Status", "Alert"]} onOpen={onOpen} rows={rows.map((row) => ({ id: row.id, cells: [<strong>{row.movement.reference_number}</strong>, money.format(Number(row.amount)), formatDate(row.issued_date), formatDate(row.due_date), <span>{row.paid_date ? "—" : `${Math.max(0, daysBetween(row.due_date))} days`}</span>, formatDate(row.paid_date), <Badge value={row.status} />, <AlertMark active={row.active_alert} />] }))} />; }
function Table({ headers, rows, onOpen }: { headers: string[]; rows: Array<{ id: string; cells: React.ReactNode[] }>; onOpen: (id: string) => void }) { const activate = (event: React.KeyboardEvent, id: string) => { if (event.key === "Enter" || event.key === " ") { event.preventDefault(); onOpen(id); } }; return <><div className="hidden overflow-x-auto md:block"><table className="w-full text-left text-sm tabular-nums"><thead className="bg-ajs-bg/60 text-[11px] uppercase tracking-wider text-ajs-secondary"><tr>{headers.map((header) => <th className="px-4 py-3" key={header}>{header}</th>)}</tr></thead><tbody>{rows.map(({ cells, id }) => <tr className="cursor-pointer border-t border-ajs-border transition-colors hover:bg-ajs-border/25" key={id} onClick={() => onOpen(id)} onKeyDown={(event) => activate(event, id)} tabIndex={0}>{cells.map((cell, cellIndex) => <td className="px-4 py-4" key={cellIndex}>{cell}</td>)}</tr>)}</tbody></table></div><div className="grid gap-3 p-3 md:hidden">{rows.map(({ cells, id }) => <article className="cursor-pointer rounded-lg border border-ajs-border border-l-4 border-l-ajs-low bg-ajs-bg/40 p-4 transition-colors hover:bg-ajs-border/25" key={id} onClick={() => onOpen(id)} onKeyDown={(event) => activate(event, id)} role="button" tabIndex={0}>{cells.map((cell, cellIndex) => <div className="flex justify-between gap-5 border-b border-ajs-border/70 py-2 last:border-0" key={cellIndex}><span className="text-xs text-ajs-secondary">{headers[cellIndex]}</span><span className="text-right text-sm">{cell}</span></div>)}</article>)}</div></>; }
